# Meta Data for SEO

metaautor = "Tim&Koko AG - hallo@tim-koko.ch"
metacopyright = "Tim&Koko AG - hallo@tim-koko.ch"

## Homepage
title = "tim&koko"
titleSeparator = "-"
titleAddition = "into the cloud"
description = ""

## Open Graph
images = ["timkoko_og.png"]
ogLocale = "de_CH"
titleHome = ""

## Twitter Cards
twitterSite = "@tim_und_koko"
twitterCreator = "@tim_und_koko"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "tim-koko"
schemaAuthor = "tim-koko"
schemaAuthorTwitter = "https://twitter.com/tim_und_koko"
schemaAuthorLinkedIn = "https://www.linkedin.com/company/tim-koko/"
schemaAuthorGitHub = "https://github.com/tim-koko"
schemaLocale = "de-CH"
schemaLogo = "logo-timkoko.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "timkoko_og.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/tim_und_koko"
schemaLinkedIn = "https://www.linkedin.com/company/tim-koko/"
schemaGitHub = "https://github.com/tim-koko"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Footer
footer = '<a href="mailto:hallo@tim-koko.ch">hallo@tim-koko.ch</a>'

# Feed
copyRight = ""

# Alert
alert = true
alertDismissable = true
alertText = ""

# lazyimg
[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  maxSize = "1920x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = ""
  noscript = true

  errorHandler = "warning"

# Images (@thulite/images)
[thulite_images]
  [thulite_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default) 
    loading = "lazy" # eager or lazy (default)
    widths = [480, 576, 768, 1025, 1200, 1440] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "auto" # 100vw (default), 75vw, or auto for example
    process = "" # "fill 1600x900" or "fill 2100x900" for example
    lqip = "16x webp q20" # "16x webp q20" or "21x webp q20" for example

  [thulite_images.landscape]
    normalize = "1600x1200" # "1360x765" # "1600x900" (default)
    widths = [480, 576, 768, 1025, 1200, 1440] # [480, 640, 800, 1024]
  [thulite_images.portrait]
    normalize = "765x1360" # "900x1600" (default)
    lqip = "9x16" # "9x16" (default)
    widths = [480, 640, 800, 1024]
